### ISSUE TITLE
Add YouTube DL function

### ISSUE THREAD

**Issue by alexellis** [openfaas/store-functions#5]
GitHub restored YouTube DL after its original DMCA notice, therefore we can add back the YouTube DL function to the store.

Submit a tested PR to this repository based upon my example here: https://github.com/faas-and-furious/youtube-dl/blob/master/Dockerfile

Then once merged, let's add it to the store manifest file: https://github.com/openfaas/store

**Comment by alexellis** [comment]
/add label: help wanted, good first issue

**Comment by cpanato** [comment]
i can try this one

**Comment by alexellis** [comment]
Thanks @cpanato - added via [ff1a461](https://github.com/openfaas/store-functions/commit/ff1a4611c5e90b1deb0aa51eb9abf80bdd1c8b41)
